SCREEN 12
INPUT "Schnell oder langsam (s, l)"; s$
IF s$ = "s" THEN PLAY "T255"
CLS
PRINT "Deutschland, Deutschland, ber alles,"
PRINT "ber alles in der Welt,"
PRINT "wenn es stets zum Schutz und Trutze"
PRINT "brderlich zusammenh„lt,"
PRINT "von der Maas bis an die Memel,"
PRINT "von der Etsch bis an den Belt."
PRINT "³: Deutschland, Deutschland ber alles,"
PRINT "ber alles in der Welt. :³"
PRINT
PRINT "Deutsche Frauen, deutsche Treue,"
PRINT "deutscher Wein und deutscher Sang"
PRINT "sollen in der Welt behalten"
PRINT "ihren alten, sch”nen Klang."
PRINT "Uns zu edler Tat begeistern,"
PRINT "unser ganzes Leben lang:"
PRINT "³: Deutsche Frauen, deutsche Treue,"
PRINT "deutscher Wein und deutscher Sang. :³"
PRINT
PRINT "Einigkeit und Recht und Freiheit"
PRINT "fr das deutsche Vaterland!"
PRINT "Danach lasst uns alle streben"
PRINT "brderlich mit Herz und Hand!"
PRINT "Einigkeit und Recht und Freiheit"
PRINT "sind des Glckes Unterpfand."
PRINT "³: Blh im Glanze dieses Glckes,"
PRINT "blhe deutsches Vaterland! :³"

PLAY "O2L4e-.L8fL4gfa-gL8fdL4e->c<b-a-gfL8ge-L2b-"
PLAY "L4e-.L8fL4gfa-gL8fdL4e->c<b-a-gfL8ge-L2b-"
PLAY "L4fgL8fdL4<b->a-gL8fdL4<b->b-a-g.L8gL4aL8ab-L2b-"
PLAY "L4>e-.L8ddcL4<b->c.<L8b-b-a-L4gf.L16ga-L8b->c<a-fL4e-L8gfL2e-"
PLAY "L4>e-.L8ddcL4<b->c.<L8b-b-a-L4gf.L16ga-L8b->c<a-fL4e-L8gfL2e-P1"

DO: LOOP WHILE INKEY$ = ""

