


















CLS
PRINT "Hi Rafi!"
PRINT
INPUT "", a$  'Hi Compi
PRINT
PRINT "Hey nenn mich nicht Compi!"
PRINT
INPUT "", a$, B$ 'OK. Guten Tag Genosse, wie geht's?
PRINT
PRINT "Oh ja, Genosse finde ich besser.";
FOR x = 1 TO 200000: NEXT x
PRINT " Mir geht's so einigermaáen gut.";
FOR x = 1 TO 200000: NEXT x
PRINT " Und wie gehts dir?"
PRINT
INPUT "", a$  'so lala
PRINT
PRINT "Was heisst hier >so lala< ?"
FOR x = 1 TO 200000: NEXT x
PRINT "Antworte mal vernnftig!"
PRINT
INPUT "", a$  'Mir gehts gut!
PRINT
PRINT "Aha, dann gratuliere!"
PRINT
INPUT "", a$  'wozu?
PRINT
PRINT "Dazu, dass es dir gut geht."
FOR x = 1 TO 200000: NEXT x
PRINT "Moment mal, wer ist das da eigentlich?"
PRINT
INPUT "", a$  'Meine Freunde!
PRINT
PRINT "Dachte ich mir schon!"
PRINT
INPUT "", a$  'Warum?
PRINT
PRINT "Siehst du nicht den beh„mmerten Blick!"
PRINT
INPUT "", a$  'Na und?
PRINT
PRINT "Was, Na und? Sowas lenkt mich ab!"
PRINT
INPUT "", a$  'Dann kuck' doch weg!
PRINT
PRINT "Wieso, sollen die sich doch verpissen!"
PRINT
INPUT "", a$  'Sollen sie nicht!
PRINT
PRINT "Ph, dann streike ich. Bis morgen!"
PRINT
INPUT "", a$  'Morgen binn ich nicht da!
PRINT
PRINT "Dann halt bis bermorgen!"
PRINT "P.S.: >bin< schreibt man mit einem >n<!"
PRINT
INPUT "", a$  'Exit

