
'Spielt 2 Lieder mit PLAY

CLS
PRINT "                      L I E D"
PRINT "                      -------"
PRINT "Welches Lied willst du hîren? (Bitte gib die Nummer ein!)"
PRINT "             FÅr Alle meine Entchen die  1"
PRINT "             FÅr HÑnschen klein die      2"
INPUT Zahl
IF Zahl = 1 THEN PLAY "L8cdefL4ggL8aaaaL2gL8aaaaL2gL8ffffL4eeL8ggggL2c"
IF Zahl = 2 THEN PLAY "L8geL4eL8fdL4dL8cdefggL4gL8geL4eL8fdL4dL8ceggL2cL8dddddeL4fL8eeeeefL4gL8geL4eL8fdL4dL8ceggL2c"
END

