



















CLS
COLOR 0, 7
PRINT "   Datei  Bearbeiten  Ansicht  Suchen  Ausfhren  Debug  Optionen     Hilfe     "
COLOR 2, 0
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ           ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ ÃÄ¿"
FOR x = 1 TO 18
 PRINT "³"; SPACE$(78); "³"
NEXT x
PRINT "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ Direkt ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´"
PRINT "³"; SPACE$(78); "³"
PRINT "³"; SPACE$(78); "³"
COLOR 15, 3
PRINT " UMSCH+F1=Hilfe  F6=Fenster  F2=SUBs  F5=Ausf  F8=Schritt     ";
COLOR 0, 3
PRINT "³     N 00001:001 ";
COLOR 0, 10
LOCATE 2, 35
PRINT " Unbenannt "
LOCATE 2, 77
PRINT ""
LOCATE 3, 2, 1, 30, 31
SLEEP
COLOR 0, 0

