' Hallo und Herzlich willkommen zu diesem Tutorial!

' Ich hoffe, dass ich hier nach und nach erkl„ren kann,
' wie man mit QBasic programmiert.

' Alles hinter einem Hochkomma - so wie dieser Text - wird nicht ausgefhrt,
' Deswegen stehen all meine Erkl„rungen hinter Hochkommata.


' Dieser Befehl schreibt 'Hallo Welt.' auf den Bildschirm.

PRINT "Hallo Welt."


' Um nicht so viel zu tippen kann man auch '? "Hallo"' eingeben
' Der Interpreter (das Programm, dass die Programme ausfhrt) ersetzt
' Das dann automatisch.

' Um ein geschriebenes Programm auszufhren, drcke einfach [F5].

' Wenn du das Programm ein paar mal ausgefhrt hast, merkst du, dass
' der Bildschirm noch vom letzten ausfhren zu sehen ist.
' Um alle bisher (ob bei frherem ausfhren oder beim aktuellen
' Programmlauf, das ist egal) ausgegebenen Zeichen zu l”schen, schreibe
' CLS in die Zeile vor den PRINT-Befehl.
' Das bedeutet CLear Screen und l”scht den Bildschirm.

' Mehr lernst du im n„chsten tut.
' Ich vermute mal, dass du das ™ffnen und Speichern und so selber hinbekommst.

' Soviel erstmal zu diesem ersten Programm.

